/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardLicensesRouteImport } from './routes/dashboard/licenses'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardLicensesIndexRouteImport } from './routes/dashboard/licenses/index'
import { Route as DashboardLicensesLicenseIdRouteImport } from './routes/dashboard/licenses/$licenseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicensesRoute = DashboardLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicensesIndexRoute = DashboardLicensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLicensesRoute,
} as any)
const DashboardLicensesLicenseIdRoute =
  DashboardLicensesLicenseIdRouteImport.update({
    id: '/$licenseId',
    path: '/$licenseId',
    getParentRoute: () => DashboardLicensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/licenses': typeof DashboardLicensesRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/licenses/$licenseId': typeof DashboardLicensesLicenseIdRoute
  '/dashboard/licenses/': typeof DashboardLicensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/licenses/$licenseId': typeof DashboardLicensesLicenseIdRoute
  '/dashboard/licenses': typeof DashboardLicensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/licenses': typeof DashboardLicensesRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/licenses/$licenseId': typeof DashboardLicensesLicenseIdRoute
  '/dashboard/licenses/': typeof DashboardLicensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/licenses'
    | '/dashboard/products'
    | '/dashboard/'
    | '/dashboard/licenses/$licenseId'
    | '/dashboard/licenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/products'
    | '/dashboard'
    | '/dashboard/licenses/$licenseId'
    | '/dashboard/licenses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/licenses'
    | '/dashboard/products'
    | '/dashboard/'
    | '/dashboard/licenses/$licenseId'
    | '/dashboard/licenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licenses': {
      id: '/dashboard/licenses'
      path: '/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof DashboardLicensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licenses/': {
      id: '/dashboard/licenses/'
      path: '/'
      fullPath: '/dashboard/licenses/'
      preLoaderRoute: typeof DashboardLicensesIndexRouteImport
      parentRoute: typeof DashboardLicensesRoute
    }
    '/dashboard/licenses/$licenseId': {
      id: '/dashboard/licenses/$licenseId'
      path: '/$licenseId'
      fullPath: '/dashboard/licenses/$licenseId'
      preLoaderRoute: typeof DashboardLicensesLicenseIdRouteImport
      parentRoute: typeof DashboardLicensesRoute
    }
  }
}

interface DashboardLicensesRouteChildren {
  DashboardLicensesLicenseIdRoute: typeof DashboardLicensesLicenseIdRoute
  DashboardLicensesIndexRoute: typeof DashboardLicensesIndexRoute
}

const DashboardLicensesRouteChildren: DashboardLicensesRouteChildren = {
  DashboardLicensesLicenseIdRoute: DashboardLicensesLicenseIdRoute,
  DashboardLicensesIndexRoute: DashboardLicensesIndexRoute,
}

const DashboardLicensesRouteWithChildren =
  DashboardLicensesRoute._addFileChildren(DashboardLicensesRouteChildren)

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardLicensesRoute: typeof DashboardLicensesRouteWithChildren
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardLicensesRoute: DashboardLicensesRouteWithChildren,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
